# Language
language: java
# User-mode
sudo: false

# JDK
jdk:
- openjdk11

# JaCoCo statistics
# service: https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

# Sends e-mail if assembly success or fail.
notifications:
  email:
    recipients:
    - artress@ngs.ru
    on_success: always # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN=c5203570-cc7b-4c25-84a5-d8df91abcd4a

# Start MySQL
services:
- mysql
before_install:
- mysql -u root  -e 'CREATE DATABASE avito;'